"use client";

import { useState } from "react";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Lightbulb, Send } from "lucide-react";
import Link from "next/link";

export default function StakeholderPortal() {
  const [message, setMessage] = useState("");
  async function register(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/stakeholders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organization: form.get("organization"), contact: form.get("contact"), type: form.get("type") }) }); const data = await response.json(); setMessage(response.ok ? "Registration submitted. Admin verification is required before stakeholder access is enabled." : data.error); if (response.ok) event.currentTarget.reset(); }
  return <div className="portal-shell"><header className="nav"><Link href="/" className="brand"><span className="brand-mark"><Lightbulb size={17} /></span>JanNirmaan</Link><Link href="/" className="back-link"><ArrowLeft size={15} /> Public board</Link></header><main className="portal-content"><div className="portal-hero"><div><div className="eyebrow">Stakeholder partnership portal</div><h1>Support solutions with context, capital, and connections.</h1><p className="muted">Industry, CSR, investor, and government partners can register to mentor teams, fund pilots, or provide implementation pathways.</p></div><div className="portal-icon"><BriefcaseBusiness size={30} /></div></div><section className="card narrow-card"><h2>Register as a stakeholder</h2><p className="muted">Tell us how your organization can contribute. Access is enabled only after admin verification.</p>{message && <div className="success-note"><CheckCircle2 size={16} /> {message}</div>}<form className="form-grid" onSubmit={register}><div className="field"><label>Organization</label><input className="input" name="organization" placeholder="Company, CSR foundation, department..." required /></div><div className="config-row"><div className="field"><label>Contact email</label><input className="input" type="email" name="contact" placeholder="partnerships@org.in" required /></div><div className="field"><label>Partner type</label><select className="select" name="type" defaultValue="Industry"><option>Industry</option><option>CSR organization</option><option>Investor</option><option>Government department</option><option>Mentor</option></select></div></div><button className="primary" type="submit"><Send size={15} /> Submit registration</button></form></section></main></div>;
}
